global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prysm'
    static_configs:
      - targets: ['host.docker.internal:8080', 'host.docker.internal:8081', 'host.docker.internal:8082']

  - job_name: 'geth'
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ['host.docker.internal:6060', 'host.docker.internal:6061', 'host.docker.internal:6062']
